/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guessing.gui.game;

import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author LENOVO
 */
public class Player extends javax.swing.JFrame {

    /**
     * Creates new form Player
     */
    Random randomNumberGenerator = new Random();
    int tryingTime = 1;
    String guessedNumber = "";
    
    public Player() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new java.awt.Label();
        txtStartingNumber = new java.awt.TextField();
        label2 = new java.awt.Label();
        txtEndingNumber = new java.awt.TextField();
        clearGuess = new java.awt.Button();
        guessNewNumber = new java.awt.Button();
        userGuess = new java.awt.TextField();
        computerGuess = new java.awt.TextField();
        txtUserGuess = new java.awt.TextField();
        txtComputerGuess = new java.awt.TextField();
        wonInfo = new java.awt.TextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        label1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        label1.setText("Starting Number");

        txtStartingNumber.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtStartingNumber.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtStartingNumber.setText("1");

        label2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        label2.setText("Ending Number");

        txtEndingNumber.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtEndingNumber.setText("100");

        clearGuess.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        clearGuess.setForeground(new java.awt.Color(100, 100, 100));
        clearGuess.setLabel("Clear Guess");
        clearGuess.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clearGuessMouseClicked(evt);
            }
        });

        guessNewNumber.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        guessNewNumber.setForeground(new java.awt.Color(100, 100, 100));
        guessNewNumber.setLabel("Guess New Number");
        guessNewNumber.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                guessNewNumberMouseClicked(evt);
            }
        });

        userGuess.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        userGuess.setText("User Guess");

        computerGuess.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        computerGuess.setText("Computer Guess");

        txtUserGuess.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        wonInfo.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        jMenu1.setText("help");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtStartingNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEndingNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtUserGuess, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(userGuess, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(clearGuess, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 337, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(guessNewNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 337, Short.MAX_VALUE)
                            .addComponent(computerGuess, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtComputerGuess, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addComponent(wonInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(225, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtStartingNumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtEndingNumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(clearGuess, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(guessNewNumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(userGuess, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(computerGuess, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtUserGuess, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtComputerGuess, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(71, 71, 71)
                .addComponent(wonInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clearGuessMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearGuessMouseClicked
        // TODO add your handling code here:
        txtUserGuess.setText("");
        txtComputerGuess.setText("");
    }//GEN-LAST:event_clearGuessMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        randomNumberGenerator.setSeed(Integer.valueOf(txtStartingNumber.getText()));
    }//GEN-LAST:event_formWindowOpened

    private void guessNewNumberMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guessNewNumberMouseClicked
        // TODO add your handling code here:
        if(tryingTime == 1){
            guessedNumber = String.valueOf(randomNumberGenerator.nextInt(Integer.valueOf(txtEndingNumber.getText())));
            txtComputerGuess.setText("") ;
        }
        
        tryingTime ++;
        String help = "";
    /*    for(int i = 10; i > 0; i--){
            //boolean hasWon = (txtUserGuess.getText().equals(txtComputerGuess.getText()));
            wonInfo.setText((Integer.valueOf(txtUserGuess.getText())>Integer.valueOf(txtComputerGuess.getText()))?"It is less":"It is more");
        }
    */    
        
        try{
            boolean hasWon = (txtUserGuess.getText().equals(guessedNumber));
            
            if(Integer.valueOf(txtUserGuess.getText()) > Integer.valueOf(guessedNumber))
                help = "It is less";
            else if(Integer.valueOf(txtUserGuess.getText()) < Integer.valueOf(guessedNumber))
                help = " It is more";
            System.out.println(guessedNumber);
            wonInfo.setText("You have " + (10 - tryingTime) + " guess(es) left" + "\n");
            Thread.sleep(500);
            wonInfo.setText(help);
            
            if(tryingTime > 10 && !hasWon){
                tryingTime = 1;
                txtComputerGuess.setText(guessedNumber) ;
                JOptionPane.showMessageDialog(null, "Sorry, you have lost");
            }
            else if(tryingTime <= 10 && hasWon){
                tryingTime = 1;
                txtComputerGuess.setText(guessedNumber) ;
                JOptionPane.showMessageDialog(null, "Congratulation, you have won");
            }
        } catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Please Enter a User Guess Number before clicking on Guess New Number");
        } catch(Exception p){
            
        }  
            
    }//GEN-LAST:event_guessNewNumberMouseClicked

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        // TODO add your handling code here:
        String help = "The computer has generated a random number between a beginning number and an ending number.\n"
                + "Enter a User Guess Number then press en Guess New Number.\n"
                + "You'll be make known if the number you entered is less or more than the generated computer number.\n"
                + "You have Ten guess";
        JOptionPane.showMessageDialog(null, help);
    }//GEN-LAST:event_jMenu1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Player.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Player.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Player.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Player.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Player().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button clearGuess;
    private java.awt.TextField computerGuess;
    private java.awt.Button guessNewNumber;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.TextField txtComputerGuess;
    private java.awt.TextField txtEndingNumber;
    private java.awt.TextField txtStartingNumber;
    private java.awt.TextField txtUserGuess;
    private java.awt.TextField userGuess;
    private java.awt.TextField wonInfo;
    // End of variables declaration//GEN-END:variables
}
